spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 272313
    url: jdbc:mysql://47.102.223.168:3306/root_test?characterEncoding=utf8&serverTimezone=Asia/Shanghai
  redis:
    url: redis://47.102.223.168:6379
    password: 272313

